branches:
  only:
    - master

language: python
python:
  - "2.7"
  - "3.5"

cache:
  - pip

before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "tay@taybird.com"
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
install:
  - "pip install -r requirements.txt"
  - "python setup.py develop"
script:
  - "cd tests"
  - "nosetests"
  - "cd ../"
  - "make -C docs html"
after_success:
  - env GITHUB_TOKEN="${CI_USER_TOKEN}" python travis_after_all.py https://api.travis-ci.org
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
          echo "All jobs succeeded! PUBLISHING..."
          git subtree push --prefix docs/_build/html origin gh-pages
        else
          echo "Some jobs failed"
        fi
      fi
after_script:
  - echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
