branches:
  only:
    - master

language: python
python:
  - "2.7"

before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "tay@taybird.com"
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
install:
  - "pip install -r requirements.txt"
script:
  - "cd tests; nosetests; cd ../"
  - "make html"
